In [2]:
import numpy as np

In [8]:
#9


x=np.array([[6,7,4,7,8],[4,5,3,2,1],[5,6,8,9,0]])
print(x[1,1:4])

[5 3 2]


In [43]:
x=np.array([[6,7,4,7,8],[4,5,3,2,1],[5,6,8,9,0]])
print(x[0,0:3])
print(x[1,0:3])
print(x[2,0:3])

[6 7 4]
[4 5 3]
[5 6 8]


In [37]:
x=np.array([[6,7,4,7,8],[4,5,3,2,1],[5,6,8,9,0]])
print(x[::-1])

[[5 6 8 9 0]
 [4 5 3 2 1]
 [6 7 4 7 8]]


In [45]:
#10

arr=np.arange(20,45,3)
arr




array([20, 23, 26, 29, 32, 35, 38, 41, 44])

In [46]:
#11 

arr=np.zeros(64)
arr=arr.reshape(8,8)
arr[1::2, ::2]=1
arr[::2, 1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [47]:
#12

a=[1,2,3,4,5,6,7,8]
b=([8,4,6],[1,2,3])
arr=np.array(a)
arr1=np.array(b)
print(type(arr))
print(type(arr1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [75]:
#13

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
arr[1,1,1]=0
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  0]],

       [[ 9, 10],
        [11, 12]]])

In [54]:
#14

a=np.array([1.1,1.2,1.3],dtype="int")
a

array([1, 1, 1])

In [58]:
#15


arr=np.zeros(49)
arr=arr.reshape(7,7)
arr[1:-1,1:-1]=1
arr[2:-2,2:-2]=2
arr[3:4,3:4]=3
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [77]:
#16

a=np.array([[[5,6,7],[7,8,9]],[[0,4,8],[2,3,1]],[[9,5,3],[0,4,5]]])
a[0,1,1]=0
a[1,1,1]=0
a[2,1,1]=0
a

array([[[5, 6, 7],
        [7, 0, 9]],

       [[0, 4, 8],
        [2, 0, 1]],

       [[9, 5, 3],
        [0, 0, 5]]])

In [79]:
b=np.array([[[11,10,12],[88,0,45]],[[90,78,33],[41,77,0]],[[8,9,90],[12,67,9]]])
b[0,0,0]=0
b[0,0,2]=0
b[1,0,0]=0
b[1,0,2]=0
b[2,0,0]=0
b[2,0,2]=0
b
arr[1::2, ::1]=1

array([[[ 0, 10,  0],
        [88,  0, 45]],

       [[ 0, 78,  0],
        [41, 77,  0]],

       [[ 0,  9,  0],
        [12, 67,  9]]])

In [116]:
#17

arr=np.zeros(42)
arr=arr.reshape(6,7)
arr[::3, 1::2]=1
arr[2::3, ::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])